Content:
    tutorial:
        root_dir: ${ROOT_DIR}/doc/workshops
    moose:
        root_dir: ${MOOSE_DIR}/framework/doc/content
        content:
            - ../../../tutorials/darcy_thermo_mech/doc/content/workshop/intro/moose_introduction.md

Executioner:
    type: MooseDocs.base.Serial

Renderer:
    type: MooseDocs.base.RevealRenderer
    theme: simple

Extensions:
    disable_defaults: True
    MooseDocs.extensions.reveal:
        translate: tutorial/index.md
        background_image: ncsu_slide_background.png
    MooseDocs.extensions.comment: default
    MooseDocs.extensions.command: default
    MooseDocs.extensions.bibtex: default
    MooseDocs.extensions.alert: default
    MooseDocs.extensions.core: default
    MooseDocs.extensions.config: default
    MooseDocs.extensions.media: default
    MooseDocs.extensions.floats: default
    MooseDocs.extensions.include: default
    MooseDocs.extensions.style: default
    MooseDocs.extensions.autolink: default
    MooseDocs.extensions.materialicon: default
    MooseDocs.extensions.heading: default
    MooseDocs.extensions.shortcut: default
    MooseDocs.extensions.table: default
    MooseDocs.extensions.layout: default
    MooseDocs.extensions.content: default
    MooseDocs.extensions.modal: default
    MooseDocs.extensions.listing: default
    MooseDocs.extensions.datetime: default
    MooseDocs.extensions.katex:
        macros: !include ${MOOSE_DIR}/modules/doc/katex_macros.yml
