# This YML file is used within the Generate Zapdos Website action to setup the build environment for Zapdos.
# See .github/workflows/generate_website.yml
channels:
  - https://conda.software.inl.gov/public
dependencies:
  - moose-dev
